### ISSUE TITLE
Build error with GCC 10

### ISSUE THREAD

**Issue by smuzaffar** [fermitools/frontier#34]
We are trying to integrated GCC 10.1 in https://github.com/cms-sw/cmsdist . GCC now use `'-fno-common` ( https://gcc.gnu.org/gcc-10/porting_to.html ) as default and this break frontier cleint build. Currenlty we are able to build by passin `-fcommon` ( https://github.com/cms-sw/cmsdist/pull/5870/files ) but it would be nice to get the frontier client code properly ported to GCC 10.

**Comment by DrDaveD** [comment]
Shahzad,

If I try it with the default gcc compiler on sl7 (gcc 4.8.5) I get the errors
```
.libs/frontier.o:(.bss+0x18): multiple definition of `frontier_mem_alloc'
.libs/frontier_config.o:(.bss+0x0): first defined here
.libs/frontier.o:(.bss+0x20): multiple definition of `frontier_mem_free'
.libs/frontier_config.o:(.bss+0x8): first defined here
```
Is that the same errors you see with gcc10?

Is gcc10 easily available to me on sl7 to try it?  I see /cvmfs/cms.cern.ch/slc7_amd64_gcc10 but don't see the compiler itself there.

Otherwise I made a PR #35 to fix the above error, please test it for me.

Dave

**Comment by smuzaffar** [comment]
@DrDaveD , yes these were the exact errors we saw and I confirm that #35 builds fine with gcc 10 (without passing `-fcommon`)

**Comment by DrDaveD** [comment]
Ok, so should I make a new release for just this or include it in whatever the next release is?

**Comment by smuzaffar** [comment]
No, there is no hurry to make a release. Just include it in next release.

**Comment by DrDaveD** [comment]
Ok, will do.
